name: Delete Package Versions
on: workflow_dispatch

jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/delete-package-versions@v2.0.1
        with:
          owner: yang-xiangdong
          repo: rpc
          package-name: cn.uestc.ew.rpc

      - uses: actions/delete-package-versions@v2.0.1
        with:
          owner: yang-xiangdong
          repo: rpc
          package-name: cn.uestc.ew.rpc-common

      - uses: actions/delete-package-versions@v2.0.1
        with:
          owner: yang-xiangdong
          repo: rpc
          package-name: cn.uestc.ew.rpc-registry

      - uses: actions/delete-package-versions@v2.0.1
        with:
          owner: yang-xiangdong
          repo: rpc
          package-name: cn.uestc.ew.rpc-client

      - uses: actions/delete-package-versions@v2.0.1
        with:
          owner: yang-xiangdong
          repo: rpc
          package-name: cn.uestc.ew.rpc-server
